language: node_js
branches:
  only:
    - master
node_js:
 - "node"
install:
 - npm install
script:
  - npm run build
  - wt create ./build/min/omnibus.bundle.min.js --secrets-file .deploy.env --token $WT_TOKEN
  