language: node_js
branches:
  only:
    - master
node_js:
 - "node"
install:
 - npm install
script:
  - npm run build
deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    branch: master
  